### ISSUE TITLE
Make Website mobile friendly

### ISSUE THREAD

**Issue by Daniele122898** [Daniele122898/sora-request#2]

**Comment by Serraniel** [comment]
Ideas:

* Add another section in the requests page for completed (that means either accepted or rejected) submissions sort by completion date descending. Optional: two sections for each, accepted and rejected.
* Display a timer until next request can be made.

**Comment by Daniele122898** [comment]
i will create a seperate issue for this. as its not part of the mobile work i need to do

**Comment by Serraniel** [comment]
Ay, sorry, I overrread the *mobile* :D
